#!/usr/bin/env python3
"""Build the phase-1 analysis plan from normalized CodeQL facts.

This stage intentionally does not call an LLM. It applies a tiny rule set to
demo/output/codeql/facts.json and writes demo/output/analysis.json.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_FACTS = ROOT / "demo" / "output" / "codeql" / "facts.json"
DEFAULT_ANALYSIS = ROOT / "demo" / "output" / "analysis.json"

# -----------------------------------------------------------------------
# LLM-simulated analysis rules
# -----------------------------------------------------------------------
# In production every value below would be generated by an LLM reviewing
# the CodeQL facts (facts.json).  For this demo they are hand-written to
# keep the pipeline deterministic and self-contained.
#
# The data contract is analysis.json — downstream tools (instrument.py,
# solve.py, generate_harness.py, run_demo.py) read ONLY from that file.
# -----------------------------------------------------------------------

ENTRY_FUNCTION = "avdtp_process_configuration"
INPUT_LIKE = {"buf"}
DERIVED_CONTEXT_LIKE = {"sep"}
BUG_MARKER_PATTERNS = (
    ("buf->len -= 1", "length_decrement_without_check", "buffer length is decremented before reading"),
    ("return *buf->data++", "data_deref_after_pull", "buffer data pointer is dereferenced and advanced"),
)

# trace_vars for each critical branch, keyed by line number.
# In production this would be generated by an LLM analysing the source.
TRACE_VARS: dict[int, list[dict[str, object]]] = {
    135: [
        {
            "name": "msg_type",
            "expr": "msg_type",
            "type": "uint8_t",
            "fmt": "%u",
            "cast": "(unsigned)",
            "expected": "BT_AVDTP_CMD",
            "expected_val": 0,
            "op": "==",
            "kind": "context",
            # how the harness controls this: data[0] directly carries msg_type
            "context_mechanism": {"type": "input_byte", "byte": 0},
        }
    ],
    141: [
        {
            "name": "sep",
            "expr": "sep",
            "type": "pointer",
            "fmt": "%p",
            "cast": "(void*)",
            "expected": "non-NULL",
            "op": "!=",
            "kind": "context",
            "context_mechanism": {"type": "flag_bit", "byte": 1, "mask": 1},
        },
        {
            "name": "session->ops->set_configuration_ind",
            "expr": "session->ops->set_configuration_ind",
            "type": "pointer",
            "fmt": "%p",
            "cast": "(void*)",
            "expected": "non-NULL",
            "op": "!=",
            "kind": "context",
            "context_mechanism": {"type": "flag_bit", "byte": 1, "mask": 2},
        },
    ],
    144: [
        {
            "name": "sep->state",
            "expr": "sep->state",
            "type": "uint8_t",
            "fmt": "%u",
            "cast": "(unsigned)",
            "expected": "AVDTP_STREAMING",
            "expected_val": 4,
            "op": "!=",
            "kind": "context",
            # satisfied by default (sep_obj is memset to 0 = AVDTP_IDLE)
            "context_mechanism": {"type": "default", "note": "memset to 0 = AVDTP_IDLE, not STREAMING"},
        }
    ],
}

# Bug-trigger strategy: extra constraints needed to make the target bug reachable.
# In production this would be part of the LLM+CodeQL analysis output.
BUG_TRIGGER: dict[str, object] = {
    "description": "set SHORT buffer flag and use len=1 so second net_buf_pull_u8 underflows past 1-byte short_storage",
    "flag_byte": 1,
    "flag_mask": 4,
    "numeric_constraints": {
        "data[2]": 1,
        "data[3]": 4,
    },
}


def fact_key(fact: dict[str, Any]) -> tuple[Any, ...]:
    return (
        fact.get("function"),
        fact.get("line"),
        fact.get("source"),
        fact.get("text"),
        fact.get("kind"),
    )


def plan_item(fact: dict[str, Any], *, reason: str) -> dict[str, Any]:
    return {
        "function": fact["function"],
        "line": fact["line"],
        "source": fact["source"],
        "reason": reason,
        "evidence": {
            "kind": fact["kind"],
            "text": fact["text"],
        },
    }


def add_unique(items: list[dict[str, Any]], seen: set[tuple[Any, ...]], item: dict[str, Any]) -> None:
    key = (
        item.get("name"),
        item.get("function"),
        item.get("line"),
        item.get("source"),
        item.get("reason"),
    )
    if key not in seen:
        seen.add(key)
        items.append(item)


def symbol_item(fact: dict[str, Any], symbol: str, reason: str) -> dict[str, Any]:
    return {
        "name": symbol,
        "function": fact["function"],
        "line": fact["line"],
        "source": fact["source"],
        "reason": reason.format(symbol=symbol),
        "evidence": {
            "kind": fact["kind"],
            "text": fact["text"],
        },
    }


def classify_params(facts: list[dict[str, Any]], symbols: set[str], reason: str) -> list[dict[str, Any]]:
    return [
        symbol_item(fact, fact["text"], reason)
        for fact in facts
        if fact.get("kind") == "param"
        and fact.get("function") == ENTRY_FUNCTION
        and fact.get("text") in symbols
    ]


def entry_params(facts: list[dict[str, Any]]) -> set[str]:
    return {
        fact["text"]
        for fact in facts
        if fact.get("kind") == "param" and fact.get("function") == ENTRY_FUNCTION
    }


def classify_derived_context(facts: list[dict[str, Any]], symbols: set[str]) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    seen: set[tuple[Any, ...]] = set()

    for fact in facts:
        if fact.get("kind") not in {"if", "call"}:
            continue

        source = fact.get("source", "")
        for symbol in sorted(symbols):
            if symbol in source:
                add_unique(
                    items,
                    seen,
                    symbol_item(
                        fact,
                        symbol,
                        "{symbol} is derived context needed by target branches",
                    ),
                )

    return items


def build_analysis(facts_doc: dict[str, Any]) -> dict[str, Any]:
    facts = sorted(facts_doc["facts"], key=fact_key)

    critical_branches = []
    for fact in facts:
        if fact.get("kind") == "if":
            item = plan_item(fact, reason="conditional branch to trace for reachability")
            item["hook"] = "trace_branch"
            item["instrument"] = True
            tvars = TRACE_VARS.get(fact["line"])
            if tvars:
                item["trace_vars"] = tvars
            critical_branches.append(item)

    bug_markers: list[dict[str, Any]] = []
    seen_markers: set[tuple[str, int, str]] = set()
    for fact in facts:
        source = fact.get("source", "")
        for pattern, kind, reason in BUG_MARKER_PATTERNS:
            if pattern in source:
                key = (fact["function"], fact["line"], pattern)
                if key not in seen_markers:
                    seen_markers.add(key)
                    item = plan_item(fact, reason=reason)
                    item["kind"] = kind
                    item["hook"] = "trace_marker"
                    item["instrument"] = True
                    bug_markers.append(item)

    context_like = entry_params(facts) - INPUT_LIKE
    context_items = classify_params(
        facts,
        context_like,
        "{symbol} is an entry parameter treated as execution context",
    )
    context_items.extend(classify_derived_context(facts, DERIVED_CONTEXT_LIKE))

    return {
        "target": facts_doc["target"],
        "target_function": ENTRY_FUNCTION,
        "generated_by": "demo/workflow/make_analysis.py",
        "bug_trigger": BUG_TRIGGER,
        "rules": {
            "input_like": sorted(INPUT_LIKE),
            "context_like": "entry parameters except input_like, plus derived context symbols",
            "derived_context_like": sorted(DERIVED_CONTEXT_LIKE),
            "critical_branches": ["kind == if"],
            "bug_markers": [pattern for pattern, _kind, _reason in BUG_MARKER_PATTERNS],
        },
        "plan": {
            "input_like": classify_params(
                facts,
                INPUT_LIKE,
                "{symbol} is an entry parameter treated as attacker-controlled input",
            ),
            "context_like": context_items,
            "critical_branches": critical_branches,
            "bug_markers": bug_markers,
        },
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--facts", type=Path, default=DEFAULT_FACTS)
    parser.add_argument("--output", type=Path, default=DEFAULT_ANALYSIS)
    args = parser.parse_args()

    facts_path = args.facts.resolve()
    output_path = args.output.resolve()

    if not facts_path.exists():
        raise SystemExit(f"missing facts file: {facts_path}")

    analysis = build_analysis(json.loads(facts_path.read_text()))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(analysis, indent=2) + "\n")
    print(f"wrote {output_path}")


if __name__ == "__main__":
    main()
